version: "3.8"
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  secure-proxy:
    image: nginx:alpine
    container_name: secure-proxy
    depends_on:
      - juice-shop
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    entrypoint: "" # importante para que podás pasarle el comando
    volumes:
      - ./reports:/zap/wrk
